### ISSUE TITLE
errors in console with custom-component

### ISSUE THREAD

**Issue by Paul75** [pavvank/tb-carousel#1]
Hello,

I have error with custom component. See : https://stackblitz.com/edit/tb-carousel-demo

Thanks

**Comment by pavvank** [comment]
Hi, I am looking at the issue will respond as soon as possible.

**Comment by pavvank** [comment]
Try giving values of card height and width in pixels or any other unit other than %. The issue is everything is in %.

**Comment by Paul75** [comment]
oh for me I must do carousel with fullscreen ....

**Comment by Paul75** [comment]
the error in exemple is : 

ERROR
Error: Cannot read property 'heading' of undefined

**Comment by pavvank** [comment]
For full screen try using vh a vw for full screen

**Comment by pavvank** [comment]
try renaming modelObject to  _tbModelObject in CarouselComponent class. and respectively in its html.
*need to update readme.md. Working on addition of more kind of carousels. Will be up by end of this week.

**Comment by pavvank** [comment]
Tell me if your issue is resolved

**Comment by Paul75** [comment]
it seem resolved

**Comment by pavvank** [comment]
Alright. :)

**Comment by Paul75** [comment]
for see, I do this but when I can modiify CSS ? because I add 100vh and 100vw but now I see scrools and it take more for all the screen ....

**Comment by pavvank** [comment]
Use 
  cardHeight="80vh"
  cardWidth="90vw" 

and remove   
  containerWidth="100vh"
  containerHeight="100vh"

In next update sizing will be fixed.

**Comment by Paul75** [comment]
I want to have this screen (result) : https://nimb.ws/T2bVip

Can I do this ?

**Comment by pavvank** [comment]
That seems to be a graph
Yes you can make that.

**Comment by Paul75** [comment]
Not only also elements

**Comment by pavvank** [comment]
Can you connect on someother platform where i can chat, it would be easier

**Comment by Paul75** [comment]
Gmail ? Wechat ? WhatsApp ? Facebook ?

**Comment by pavvank** [comment]
gmail.
pavvank@gmail.com
